language: python

python:
  - "3.5"

env:
  global:
    - DATABASE_URL="postgres://postgres:@127.0.0.1:5432/tuttle"
  matrix:
    - PSQL_VERSION=9.5.4
services:
  - docker

before_install:
  - docker pull postgres:$PSQL_VERSION
  - sudo /etc/init.d/postgresql stop
  - docker run -d -p 127.0.0.1:5432:5432 postgres:$PSQL_VERSION

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -r

after_script:
  - coveralls
