# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuttleuser', '0002_auto_20160829_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuttleuser',
            name='token',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
