# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tuttleuser', '0003_auto_20160906_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuttleuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='tuttleuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
