# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=30)),
                ('repository_name', models.TextField(max_length=100)),
                ('repo_owner', models.TextField()),
                ('is_private', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('deploy_key', models.TextField(blank=True)),
            ],
        ),
    ]
