# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='organization',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
