# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('token', models.CharField(max_length=800, null=True, unique=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='deploykey',
            name='key',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='repository',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
