# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20160907_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='', max_length=800, unique=True),
            preserve_default=False,
        ),
    ]
