# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20160827_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
