# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20160823_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='repo_owner',
        ),
    ]
