# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20160823_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
