# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20160907_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_user_admin',
            field=models.BooleanField(default=True),
        ),
    ]
