# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_repository_is_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='is_user_admin',
            field=models.BooleanField(default=False),
        ),
    ]
