# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20160829_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploykey',
            name='key',
            field=models.CharField(max_length=800),
        ),
    ]
