# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20160829_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
